### ISSUE TITLE
Is it possible to release even it is alpha version, it works for basic keycloak integration

### ISSUE THREAD

**Issue by larrycai** [busykoala/fastapi-oidc-auth#1]
I tried this code, it works perfect with my basic keycloak integration.

Can you spend time to upload to PyPi?

**Comment by busykoala** [comment]
@larrycai sorry for not responding to your issue. There are multiple packages already on pypi, not sure there should be another one.
If you still would like to have this exact code there, feel free to do so (and use the code in the way you like).
