### ISSUE TITLE
GPL Licence?

### ISSUE THREAD

**Issue by kujiy** [busykoala/fastapi-oidc-auth#8]
@busykoala  Can you update the license from GPL to MIT?

**Comment by busykoala** [comment]
Can you elaborate on the requirements? I kinda like GPL but of course I'd be able to move to MIT if there are any good reasons for that.

**Comment by kujiy** [comment]
One of my colleagues said we couldn't use it for the company's internal service because of the GPL license. But he'd use another one, so you can close this thread now. Thanks,
